### DISCUSSION TITLE
How to add a step to the ingest/index pipeline

### DISCUSSION THREAD

**Discussion by leonkleinmann** [alephdata/aleph#4196] [General]
Hi everyone,

I'm currently trying to add a stage to the ingest pipeline of aleph but it doesn't work.
I created a service just like translate but I don't understand how I can make aleph use it's worker.

**docker-compose.yml**
```
  ai:
    image: aleph-service:ai
    build:
      context: .
    volumes:
       - archive-data:/data
       - "./services/translate/translate:/translate/translate"
       - "/:/host"
    depends_on:
      - api
      - redis
    restart: on-failure
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
       - aleph.env

```

I also changed the **settings.py**
```
        # Document processing pipeline
        self.INGEST_PIPELINE = env.to_list(
            "ALEPH_INGEST_PIPELINE", [self.STAGE_ANALYZE, self.STAGE_AI]
        )
```

This surely is not enough to make Aleph use my AI stage. 
Any help is welcome!

Thanks in Advance!
