### ISSUE TITLE
Replace Links with something more node-y

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#220]
eg. Call the top level generic object something like `Event` or `Relationship`.

Then model things like `directedBy` as:

* [ Person ]
  * id -> "abcd"
  * name -> "Bob Smith"
  * dob -> "1950-01-01"
  * directorship -> [ 1234 ]
* [ Company ]
  * id -> "efgh"
  * name -> "Acme Inc."
  * established -> "1920-02-02"
  * directorship -> [ 1234 ]
* [ Directorship ]
  * id -> "1234"
  * startDate -> "1980-03-03"
  * endDate -> "1990-04-04"
  * directedBy -> [ abcd ]
  * directorOf -> [ efgh ]
  * appointedBy -> [ wxyz ]

Possibly supersedes #216

**Comment by rhiaro** [comment]
First pass draft, which I think covers everything:

```
###################################################################
#
# Entity types.
#
###################################################################

  Entity:
    hidden: true
    icon: fa-circle
    properties:
      name:
        label: "Name"
        type: name
        hidden: true
      summary:
        label: "Summary"
      description:
        label: "Description"
      country:
        label: "Country"
        type: country
      alias:
        label: "Other name"
        type: name
        multiple: true
      previousName:
        label: "Previous name"
        type: name
        multiple: true
      weakAlias:
        label: "Weak alias"
        multiple: true
      sourceUrl:
        label: "Source link"
        type: url
      icijId:
        label: "ICIJ ID"
      tags:
        label: "Relevancy"
      keywords:
        label: "Keywords"
        multiple: true
      address:
        label: "Address"
        type: address
      program: # Used by sanctions
        label: "Program"
      notes:
        label: "Notes"
      relationship:
        ref: Relationship

  Document:
    extends: Entity
    label: "Document"
    plural: "Documents"
    icon: fa-file-text
    hidden: true
    fuzzy: false

  LegalEntity:
    extends: Entity
    label: "Legal entity"
    plural: "Legal entities"
    icon: fa-user-secret
    properties:
      email:
        label: "Email"
        type: email
      phone:
        label: "Phone"
        type: phone
      website:
        label: "Website"
        type: url
      legalForm:
        label: "Legal form"
      incorporationDate:
        label: "Incorporation date"
        type: date
      dissolutionDate:
        label: "Dissolution date"
        type: date
      taxStatus:
        label: "Tax status"
      status:
        label: "Status"
      sector:
        label: "Sector"
      classification:
        label: "Classification"
      bankAccount:
        label: "Bank account"
        ref: BankAccount
      jurisdiction:
        label: "Jurisdiction"
        type: country
      mainCountry:
        label: "Country of origin"
        type: country
      identifier:
        label: "Identifier"
        ref: Identifier

  Organization:
    extends: LegalEntity
    label: "Organization"
    plural: "Organizations"
    icon: fa-university

  Person:
    extends: LegalEntity
    label: "Person"
    plural: "People"
    icon: fa-user
    properties:
      title:
        label: "Title"
      firstName:
        label: "First name"
      secondName:
        label: "Second name"
      middleName:
        label: "Middle name"
      lastName:
        label: "Last name"
      birthDate:
        label: "Birth date"
        type: date
      birthPlace:
        label: "Place of birth"
      deathDate:
        label: "Death date"
        type: date
      position:
        label: "Position"
      nationality:
        label: "Nationality"
        type: country
      gender:
        label: "Gender"

  Company:
    label: "Company"
    plural: "Companies"
    icon: fa-industry
    extends:
      - Organization
      - Asset
    properties:
      capital:

  PublicBody:
    label: "Public body"
    plural: "Public bodies"
    icon: fa-building
    extends: Organization
    fuzzy: false

  Asset:
    label: "Asset"
    plural: "Assets"
    extends: Entity
    icon: fa-car
    hidden: true
    fuzzy: false
    properties:
      value:
        label: "Value"
      valueCurrency:
        label: "Value (Currency)"
      relationship:
        ref: Relationship

  Concession:
    label: "Concession"
    plural: "Concessions"
    extends: Asset
    icon: fa-th
    fuzzy: false
    properties:
      area:
        label: "Area"
      commodities:
        label: "Commodities"

  Land:
    label: "Land"
    plural: "Lands"
    extends: Asset
    icon: fa-map
    fuzzy: false
    properties:
      address:
        label: "Address"
        type: address
      location:
        label: "Location"
      censusBlock:
        label: "Census block"
      area:
        label: "Area"
      propertyType:
        label: "Property type"
      landType:
        label: "Land type"
      createDate:
        label: "Record date"
        type: date

  Vessel:
    label: "Vessel"
    plural: "Vessels"
    extends: Asset
    icon: fa-ship
    fuzzy: false
    properties:
      type:
        label: "Vessel Type"
      flag:
        label: "Flag"
      registrationPort:
        label: "Port of Registration"
      navigationArea:
        label: "Navigation Area"
      tonnage:
        label: "Tonnage"
      grossRegisteredTonnage:
        label: "Gross Registered Tonnage"
      nameChangeDate:
        label: "Date of Name Change"
        type: date

  BankAccount:
    label: "Bank Account"
    plural: "Bank Accounts"
    extends: Asset
    icon: fa-bank
    properties:
      bankName:
        label: "Bank Name"
      accountNumber:
        label: "Account Number"
        type: identifier
      accountType:
        label: "Account Type"
      balance:
        label: "Balance"

  Identifier:
    label: "Identifier"
    extends: Asset
    properties:
      type: # eg. 
        registrationNumber
        idNumber
        taxNumber
        passport
        voenCode
        okpoCode
        innCode
        coatoCode
        vatCode
        irsCode
        ipoCode
        cikCode
        jibCode
        mbsCode
        cadastralCode
        imoNumber
        crsNumber
        callSign
        apvCode
      orgIdScheme # maybe this gets merged with types
      number

  Shares:
    label: "Shares"
    extends: Asset
    properties:
      count
      value
      currency

  Contract:
    label: "Contract"
    extends: Asset
    properties:
      totalValue
      type
      procedureNumber
      documentNumber
      decisionReason
      documentDate:
        type: date
      relationship:
        ref: Relationship
      identifier:
        ref: Identifier


###################################################################
#
# Relationship types.
#
###################################################################
  
  Relationship: # (or Link)
    label: "Relationship"
    properties:
      startDate:
        label: "Start date"
        type: date
      endDate:
        label: "End date"
        type: date
      date:
        label: "Date"
        type: date
      summary:
        label: "Summary"
      role:
        label: "Role"
      recordId:
        label: "Record ID"
      sourceUrl:
        label: "Link source"
        type: url
      subject:
        label: "Subject of the relationship"
        ref: Entity
      object:
        label: "Object of the relationship"
        ref: Entity

  Event:
    label: "Event"
    extends: Relationship
    properties: 
      location:
        label: "Location"

  CourtCase:
    label: "Court case"
    plural: "Court cases"
    extends: Event
    icon: fa-briefcase
    fuzzy: false
    properties:
      category:
        label: "Category"
      type:
        label: "Type"
      status:
        label: "Status"
      caseNumber:
        label: "Case number"
        type: identifier
      court:
        label: "Court"
      fileDate:
        label: "File date"
        type: date
      closeDate:
        label: "Close date"
        type: date
      defendant:
        ref: Entity
      plaintiff:
        ref: Entity
      ...

  Transaction:
    label: "Transaction"
    extends: Event
    properties:
      from:
        ref: Entity
      to:
        ref: Entity
      for:
        ref: Asset / Interest

  Payment:
    label: "Payment"
    extends: Transaction
    properties:
      amount
      currency
      amountUsd
      sequenceNumber
      transactionNumber
      purpose
      payerAccount:
        ref: BankAccount
      beneficiaryAccount:
        ref: BankAccount

  Interest:
    label: "Interest"
    extends: Relationship
    properties:
      position
      level
      votes

  Ownership:
    label: "Ownership"
    extends: Interest
    properties:
      percentage
      value
      status
      type
      legalBasis
      asset:
        ref: Asset
      transaction:
        ref: Transaction

  Directorship:
    label: "Directorship"
    extends: Interest
    properties:
      secretary

  Membership:
    label: "Membership"
    extends: Interest
```

Dropped:
* `controlledBy` - captured by `Interest`
* `managedBy` - can be captured by `Interest->position` I *think*..
* `linkedTo` - captured by `Relationship`
* All properties that are specific identifiers, in favour of `Identifier` entity (towards #213) with a type.
  * This might be overkill, and/or it might be useful to combine with org-id identifier schemes for companies? It might make it easier to add new identifier types but I'm not sure. It will make it easier to add extra metadata about identifying documents, like expiry dates etc.

Added:
* `Shares` - this came up in research for #216 
* `Identifier` - see above
* `Interest` - type of `Relationship` that captures `Ownership`, `Directorship` and `Membership` (common term from #216)
* `Event` - type of `Relationship` that captures `CourtCase` and `Transaction`/`Payment`

Moved:
* `Contract` to be an `Asset` - based on the existing properties this seemed more right, but maybe it's a `Transaction` after all. I'd expect `Asset`s to be connected to `Transaction`s (in this draft, via `for`).
