### ISSUE TITLE
relationship ui / api in aleph 

### ISSUE THREAD

**Issue by RMHogervorst** [alephdata/aleph#2222]
I have a silly question. I'm deploying aleph to a kubernetes cluster with severe restrictions and so the helm charts don't work that well. 
I have manually filled in all the templates but the updater does not work that well. 

My ui only shows a spinner, and nothing else. I have a feeling that the ui cannot find the api in the cluster.  The UI pod does not get any information like the APIs and convert pods etc. 

My question is this: how does the UI <https://github.com/alephdata/aleph/blob/main/helm/charts/aleph/templates/ui.yaml> know where to find the API that it should query? I don't know where to start the debugging process. 

The ui is an nginx frontend that serves /static files and I don't know how it find the rest of the info.

**Comment by davidknezic** [comment]
Do you, by any chance, have your `ui` and `api` containers defined in one single Kubernetes `Deployment`?

If so, you can make the Nginx in the `ui` container resolve the `api` hostname to `127.0.0.1`. So when it proxies API requests to `api:8000`, they'll be served by your local `api` container, which serves the api under port `8000`.

See `spec/template/spec/hostAliases`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ...
spec:
  # ...
  template:
    # ...
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - api
      containers:
      # Aleph UI
      # https://github.com/alephdata/aleph/tree/main/ui
      - name: ui
        image: alephdata/aleph-ui-production
        # ...
      # Aleph API
      # https://github.com/alephdata/aleph
      - name: api
        image: alephdata/aleph
        # ...
```
