### ISSUE TITLE
Make the UI work on mobile

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#368]
Suggestion for a quick pass to make it functional on mobile displays.

* [ ] Fix the navbar on mobile (e.g. pop search input down or trigger Blueprint JS spotlight style search)
* [ ] Move search facets into a tab or toggle.
* [ ] Have document preview open 100% screen width.

**Comment by iaincollins** [comment]
Do we want to crib from Bootstrap and do something like this?

https://getbootstrap.com/docs/4.0/layout/overview/

```css
$aleph-screen-xs-max-width: 575px;
$aleph-screen-sm-min-width: 576px;
$aleph-screen-sm-max-width: 767px;
$aleph-screen-md-min-width: 768px;
$aleph-screen-md-max-width: 991px;
$aleph-screen-lg-min-width: 992px;
$aleph-screen-lg-max-width: 1199px;
$aleph-screen-xl-min-width: 1200px;

@media (max-width: $aleph-screen-xs-max-width) {
  // Will display on very small displays only
}

@media (min-width: $aleph-screen-sm-min-width) { 
  // Will display on everything except very small displays 
}

@media (min-width: $aleph-screen-md-min-width) and (max-width: $aleph-screen-lg-max-width) { 
  // Will display on desktops, except very large ones 
}
```

I don't mind if we specify 'mobile rules first' (and specify overrides for other larger screens) or 'desktop rules first' (and then overrides for smaller screens) but may be preferable to broadly stick to doing one or the other. :-)

Most folks these days do mobile rules first, but if you have a webapp focused on the desktop the latter might be easier to maintain.
