### ISSUE TITLE
BUG: Documentation is missing adding schema folder to ingest-file

### ISSUE THREAD

**Issue by lu-kalk** [alephdata/aleph#4224]
**Describe the bug**
The [documentation](https://docs.aleph.occrp.org/developers/how-to/operations/custom-data-model/) on customizing the data model instructs you to add the `schema` folder to `api` and `worker` services in `docker-compose.yml`. But it also needs to be added to `ingest-file`.

**Expected behavior**

```
### Mount a volume

If you deploy Aleph using Docker Compose, this is the most straight-forward approach.

<Steps>
  <Step>
    Add a separate item to the `volumes` configuration of the `api` and `worker` service in `docker-compose.yml` as shown below. This will make the contents of the `my-custom-schema` directory available inside of the Docker container at `/usr/local/my-custom-schema`.

    ```yaml title="docker-compose.yml"
    api:
      # ...
      volumes:
        # ...
        - ./my-custom-schema:/usr/local/my-custom-schema # Append this line

    worker:
      # ...
      volumes:
        # ...
        - ./my-custom-schema:/usr/local/my-custom-schema # Append this line

    ingest-file:
      # ...
      volumes:
        # ...
        - ./my-custom-schema:/usr/local/my-custom-schema # Append this line
    ```
  </Step>

  <Step>
    Set the `FTM_MODEL_PATH` configuration option to point to the directory that contains your custom model, for example `/usr/local/my-custom-schema`.
  </Step>

  <Step>
    Apply the changes:

    ```sh
    docker compose -d up
    ```
  </Step>

  <Step>
    When you upgrade aleph, make sure to mount the volume aswell:

    ```sh
    docker compose run --volume <path-to-schema>:/usr/local/my-custom-schema --rm shell aleph upgrade
    ```
  </Step>
</Steps>
```

**Aleph version**


**Screenshots**


**Additional context**
[Add any other context about the problem here.](https://github.com/alephdata/followthemoney/issues/1756)
