### ISSUE TITLE
API container should run DB upgrade

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#470]
In order to get a new installation up and running, "aleph upgrade" is required to run. Which can be tricky in for example a Kubernetes setup. And a bit tricky for new people as it is not documented.

The quick part is of course to document it, but i think that this is something that perhaps the API container should do on startup. (Got a working DB connection to a empty DB? Consider it a new install and run schema stuff)

**Comment by pudo** [comment]
My understanding is that a preferred way of doing this is in k8s to define a [``job``](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) which is run once as the configuration is applied and has a policy never to restart.

Would you be up for making a job spec like that?

cf. https://github.com/zendesk/samson/issues/869

**Comment by pudo** [comment]
Here's the Kubernetes config for an upgrade job: 

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: search-upgrade
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: service-account-app
          secret:
            secretName: service-account-app
        - name: service-account-db
          secret:
            secretName: service-account-db
      containers:
        - name: search-upgrade
          image: alephdata/aleph:2.1.5
          imagePullPolicy: Always
          command: ["aleph", "upgrade"]
          resources:
            requests:
              memory: 500Mi
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/service-account.json
            - name: ALEPH_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: XXX
                  key: ALEPH_DATABASE_URI
            - name: ALEPH_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: XXX
                  key: ALEPH_OAUTH_SECRET
            - name: ALEPH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: XXX
                  key: ALEPH_SECRET_KEY
          envFrom:
            - configMapRef:
                name: XXX
          volumeMounts:
            - mountPath: /var/secrets/google
              name: service-account-app
        - name: search-db-sidecar
          image: b.gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=occrp-data:us-east1:XXXX=tcp:5432
            - -credential_file=/credentials/service-account.json
          volumeMounts:
            - mountPath: /credentials
              name: service-account-db
```
