### ISSUE TITLE
Adding followthemoney schemas

### ISSUE THREAD

**Issue by winers1290** [alephdata/aleph#563]
So I've been trying to edit to followthemoney schemas in a development install locally to try and add these 'cyber entities'.

I'm executing bash within the image: `docker exec -it "58b1779d4915" bash`, where I add the extra files. When I executed the `aleph` command, I could see that it picked up the changes, as I made a typo once and it made an exception.

I've made a test CSV and defined my YAML. When I upload the file it processes successfully, and the entry gets populated in the front end, but none of my line items within the CSV are populated, the collection is blank and showing zero entries... Here is my test YAML:

````
test:
  label: Accounts Info
  info_url: https://google.com
  category: leak
  summary: This is a dataset
  roles:
    - guest
  queries:
    - csv_url: http://192.168.0.112:8000/users.csv
      entities:
        account:
          schema: OnlineIdentity
          keys:
            - email
            - account
            - ip
          properties:
            account:
              column: account
            email:
              column: email
            ip:
              column: ip
            sourceUrl:
              column: sourceUrl
            plainPassword:
              colum: plainPassword
            hashedPassword:
              column: hashedPassword
````

Any ideas? 

---

UPDATE: Tested this with a factory default schema, and seeing the same problem, no records get uploaded. I've tested using both the `aleph bulkload` command and the client side `alephclient` command over API, and both have the same result.
